### ISSUE TITLE
DIO2 not updating to latest version on Arduino IDE

### ISSUE THREAD

**Issue by StormTrooper** [Locoduino/DIO2#2]
(Actually meant more info on Arduino IDe is not working)

In the https://github.com/Locoduino/DIO2/blob/master/library.properties

You have:

`url=https://github.com/Locoduino.org/DIO2`

This should be:
`url=https://github.com/Locoduino/DIO2`

Unless you are planning to move to url=https://github.com/Locoduino.org ?

**Comment by Trusty77** [comment]
Fixed. Thanks for the info. In fact, the file library.properties was also missing in the library zip file !
